sudo: true
language: ruby
rvm:
  - 2.2.4
matrix:
  include:
    - OPENSTUDIO_VERSION=2.4.0
      OPENSTUDIO_SHA=f58a3e1808
      RUBYLIB=/usr/Ruby
before_install: gem install bundler -v 1.16.1
before_script:
  - curl -sLO https://raw.githubusercontent.com/NREL/OpenStudio-server/develop/docker/deployment/scripts/install_openstudio.sh
  - chmod +x install_openstudio.sh
  - sudo ./install_openstudio.sh 2.4.0 f58a3e1808
script:
  - rake

